version: '3.8'

services:
  web:
    build:
      context: .
      dockerfile: Dockerfile
    restart: always
    volumes:
      - .:/app
      - static_volume:/app/staticfiles
      - media_volume:/app/media
    ports:
      - "3000:3000"
    environment:
      - DJANGO_SETTINGS_MODULE=cct.settings
      - DJANGO_SECRET_KEY=django-insecure-5na2o8-+ri!1_#c*bg9js(*3)bg7g!p8)8=6(&%bhn0uu-17c3
      - DJANGO_DEBUG=True
      - POSTGRES_HOST=cct-db
      - POSTGRES_DB=cct
      - POSTGRES_USER=postgres
      - POSTGRES_PASSWORD=qaz123wsx
      - ALLOWED_HOSTS=docmost-cct-ead.0z1o5i.easypanel.host,localhost,127.0.0.1
    depends_on:
      - cct-db

  cct-db:
    container_name: cct-db
    image: postgres:13
    restart: always
    volumes:
      - postgres_data:/var/lib/postgresql/data
    environment:
      - POSTGRES_DB=cct
      - POSTGRES_USER=postgres
      - POSTGRES_PASSWORD=qaz123wsx

volumes:
  postgres_data:
  static_volume:
  media_volume:
